document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\' />");
document.writeln("<meta name=\'viewport\' content=\'width=device-width, initial-scale=1, user-scalable=no\'>");
document.writeln("<title>安全验证</title>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<style>");
document.writeln("@media screen and (max-width: 305px) { ");
document.writeln(".captcha-root {max-width:100%;font-size: 16px;} ");
document.writeln("} ");
document.writeln("</style>");
document.writeln("<div class=\'J__captcha__\'></div>");
document.writeln("<script src=\'/_guard/rotate.js\'></script>");
document.writeln("<script>");
document.writeln("let myCaptcha = document.querySelectorAll(\'.J__captcha__\').item(0).captcha({");
document.writeln("  // 验证成功时显示");
document.writeln("  timerProgressBar: !0, // 是否启用进度条");
document.writeln("  timerProgressBarColor: \'#07f\', // 进度条颜色");
document.writeln("        title: \'安全验证\',");
document.writeln("  desc: \'拖动滑块，使图片角度为正\'  ");
document.writeln("});");
document.writeln("</script>");
document.writeln("</body>");
document.writeln("</html>");