document.writeln("<div class=\'myui-header__logo\'>");
document.writeln("						<a class=\'logo\' href=\'/\'>");
document.writeln("							<img style=\'width:200px\' class=\'img-responsive hidden-xs\' src=\'/mm123456/img/logo.gif\' />");
document.writeln("							<img style=\'width:170px\' class=\'img-responsive visible-xs\' src=\'/mm123456/img/logo.gif\' />");
document.writeln("						</a>");
document.writeln("					</div>");
document.writeln("					<ul class=\'myui-header__menu\'>");
document.writeln("						<li class=\'search-ul dropdown-hover\'>");
document.writeln("							<a href=\'javascript:void(0);\'><i class=\'fa fa-reorder\'></i></a>");
document.writeln("							<div class=\'dropdown-box bottom fadeInDown clearfix\'>");
document.writeln("								<ul class=\'item nav-list clearfix\'>");
document.writeln("									<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-warm\' href=\'/\'>首页</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/28.html\' target=\'_blank\'>少女萝莉</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/27.html\' target=\'_blank\'>女同性恋</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/1.html\' target=\'_blank\'>日韩无码</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/2.html\' target=\'_blank\'>国产精品</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/3.html\' target=\'_blank\'>日韩精品</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/4.html\' target=\'_blank\'>欧美精品</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/5.html\' target=\'_blank\'>中文字幕</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/6.html\' target=\'_blank\'>人妻系列</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/7.html\' target=\'_blank\'>制服诱惑</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/8.html\' target=\'_blank\'>强奸乱伦</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/9.html\' target=\'_blank\'>动漫精品</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/10.html\' target=\'_blank\'>自拍偷拍</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/11.html\' target=\'_blank\'>伦理影片</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/12.html\' target=\'_blank\'>AV明星</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/13.html\' target=\'_blank\'>3P合辑</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/14.html\' target=\'_blank\'>巨乳系列</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/15.html\' target=\'_blank\'>颜射系列</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/16.html\' target=\'_blank\'>口交视频</a></li>");
document.writeln("");
document.writeln("");
document.writeln("<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'/mm123456/ggggg.html\' target=\'_blank\'>艳门视频</a></li>");
document.writeln("<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'/mm123456/ggggg.html\' target=\'_blank\'>高清无码</a></li>");
document.writeln("<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'/mm123456/ggggg.html\' target=\'_blank\'>男同性恋</a></li>											");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/17.html\' target=\'_blank\'>自慰系列</a></li>");
document.writeln("																		<li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'http://mmoeid.kaav1.xyz/vod/show/id/18.html\' target=\'_blank\'>SM重味</a></li>");
document.writeln("									                                    <li class=\'col-lg-5 col-md-5 col-sm-5 col-xs-3\'><a");
document.writeln("											class=\'btn btn-sm btn-block btn-default\'");
document.writeln("											href=\'/mm123456/tz_dh.html\' target=\'_blank\'>最新地址</a></li>");
document.writeln("								</ul>");
document.writeln("							</div>");
document.writeln("						</li>");
document.writeln("						<li class=\' active hidden-sm hidden-xs\'><a href=\'/\'>首页</a></li>");
document.writeln("						<li class=\' dropdown-hover hidden-sm hidden-xs\'>");
document.writeln("														<a href=\'http://mmoeid.kaav1.xyz/vod/show/id/17.html\' target=\'_blank\'>自慰系列</a>						</li>");
document.writeln("						<li class=\' dropdown-hover hidden-sm hidden-xs\'>");
document.writeln("														<a href=\'http://mmoeid.kaav1.xyz/vod/show/id/7.html\' target=\'_blank\'>制服诱惑</a>						</li>");
document.writeln("						<li class=\' dropdown-hover hidden-sm hidden-xs\'>");
document.writeln("														<a href=\'http://mmoeid.kaav1.xyz/vod/show/id/8.html\' target=\'_blank\'>强奸乱伦</a>						</li>");
document.writeln("						<li class=\' dropdown-hover hidden-sm hidden-xs\'>");
document.writeln("														<a href=\'http://mmoeid.kaav1.xyz/vod/show/id/20.html\' target=\'_blank\'>教师学生</a>						</li>");
document.writeln("						<li class=\' dropdown-hover hidden-sm hidden-xs\'>");
document.writeln("														<a href=\'http://mmoeid.kaav1.xyz/vod/show/id/9.html\' target=\'_blank\'>动漫精品</a>						</li>");
document.writeln("");
document.writeln("					</ul>");
document.writeln("");
document.writeln("					<ul class=\'myui-header__user\'>");
document.writeln("						<li class=\'visible-xs\'>");
document.writeln("							<a class=\'open-search\' href=\'javascript:void(0);\'><i class=\'fa fa-search\'></i></a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("					<script type=\'text/javascript\' src=\'/static_ka/js/jquery.autocomplete.js\'></script>");
document.writeln("					<ul class=\'myui-header__search search-box\'>");
document.writeln("						<li class=\'search-item dropdown-hover\' href=\'javascript:void(0);\'>");
document.writeln("							<form id=\'search\' name=\'search\' method=\'get\' target=\'_blank\' action=\'http://mmoeid.kaav1.xyz/vod/search.html\'");
document.writeln("								onSubmit=\'return qrsearch();\'>");
document.writeln("								<input type=\'text\' id=\'wd\' name=\'wd\' class=\'search_wd form-control\' value=\'\'");
document.writeln("									placeholder=\'网红艳门\' autocomplete=\'off\' />");
document.writeln("								<button class=\'submit search_submit\' id=\'searchbutton\' type=\'submit\' name=\'submit\'><i");
document.writeln("										class=\'fa fa-search\'></i></button>");
document.writeln("							</form>");
document.writeln("							<div class=\'search-hot dropdown-box bottom fadeInDown\'>");
document.writeln("								<div class=\'item\'>");
document.writeln("									<p class=\'text-muted\'>");
document.writeln("										热门搜索");
document.writeln("									</p>");
document.writeln("																		<p>");
document.writeln("									    <a class=\'text-333\' target=\'_blank\' href=\'http://mmoeid.kaav1.xyz/vod/search/wd/%E9%85%92%E5%BA%97.html\' title=\'\'>");
document.writeln("									        <span class=\'badge badge-first\'>1</span> 酒店										</a>");
document.writeln("									</p>");
document.writeln("																		<p>");
document.writeln("									    <a class=\'text-333\' target=\'_blank\' href=\'http://mmoeid.kaav1.xyz/vod/search/wd/%E8%80%81%E5%B8%88.html\' title=\'\'>");
document.writeln("									        <span class=\'badge badge-first\'>1</span> 老师										</a>");
document.writeln("									</p>");
document.writeln("																		<p>");
document.writeln("									    <a class=\'text-333\' target=\'_blank\' href=\'http://mmoeid.kaav1.xyz/vod/search/wd/%E4%B9%B1%E4%BC%A6.html\' title=\'\'>");
document.writeln("									        <span class=\'badge badge-first\'>1</span> 乱伦										</a>");
document.writeln("									</p>");
document.writeln("																		<p>");
document.writeln("									    <a class=\'text-333\' target=\'_blank\' href=\'http://mmoeid.kaav1.xyz/vod/search/wd/%E4%BA%BA%E5%85%BD.html\' title=\'\'>");
document.writeln("									        <span class=\'badge badge-first\'>1</span> 人兽										</a>");
document.writeln("									</p>");
document.writeln("																	</div>");
document.writeln("							</div>");
document.writeln("						</li>");
document.writeln("						<a class=\'search-close visible-xs\' href=\'javascript:void(0);\'><i class=\'fa fa-close\'></i></a>");
document.writeln("					</ul>");