document.writeln("<header id=\'wap_header\' class=\'header navbar-fixed-top\' >");
document.writeln("  <div id=\'mobile-header\'>");
document.writeln("    <nav id=\'nav\' class=\'navbar navbar-default navbar-fixed-top navbar-custom\'>");
document.writeln("      <div class=\'container-fluid container \'>");
document.writeln("        <div class=\'navbar-header\'>");
document.writeln("          <a href=\'/\' class=\'application-name navbar-brand flex flex-centered\'>");
document.writeln("            <img src=\'/pp999/img/logo.gif\' title=\'ThePorn \' class=\'logo\'></a>");
document.writeln("          <div id=\'navbar\' class=\'cl sub-navbar\'>");
document.writeln("            <ul class=\'nav float-left\'>");
document.writeln("              <li class=\'header-search mr10 search-box\'>");
document.writeln("                <form action=\'/index.php/vod/search.html\' method=\'post\' id=\'search_form\' onsubmit=\'avshow.on_search()\' class=\'zu-top-search\'>");
document.writeln("                  <div class=\'search-box-input\'>");
document.writeln("                    <input name=\'wd\' placeholder=\'搜索\' type=\'search\' class=\'ng-pristine ng-valid form-control-ex\'></div>");
document.writeln("                </form>");
document.writeln("              </li>");
document.writeln("            </ul>");
document.writeln(" ");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("      <div role=\'navigation\' class=\'view-nav menu-container cl\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        <ul class=\'nav-list left\'>");
document.writeln("          <li class=\'nav-item\'>");
document.writeln("            <button id=\'mobile-menu-button\' class=\'ui mobile-menu-button icon button\'>");
document.writeln("              <i class=\'align justify icon\' style=\'font-size: 1.25rem; font-weight: bold;\'></i>");
document.writeln("            </button>");
document.writeln("          </li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("          <nav id=\'main-nav\' class=\'nav\'>");
document.writeln("");
document.writeln("");
document.writeln("            <li data-nav=\'categories-all\' class=\'nav-item\'>");
document.writeln("              <a href=\'/\'>首页</a></li>");
document.writeln("  ");
document.writeln("         ");
document.writeln("");
document.writeln("            <li data-nav=\'jav\' class=\'nav-item\'>");
document.writeln("              <a href=\'/index.php/vod/type/id/30.html\'>视频一区</a></li>");
document.writeln("");
document.writeln("   ");
document.writeln("         ");
document.writeln("");
document.writeln("            <li data-nav=\'jav\' class=\'nav-item\'>");
document.writeln("              <a href=\'/index.php/vod/type/id/31.html\'>视频二区</a></li>");
document.writeln("");
document.writeln("   ");
document.writeln("         ");
document.writeln("");
document.writeln("            <li data-nav=\'jav\' class=\'nav-item\'>");
document.writeln("              <a href=\'/index.php/vod/type/id/32.html\'>视频三区</a></li>");
document.writeln("");
document.writeln("   ");
document.writeln("         ");
document.writeln("");
document.writeln("            <li data-nav=\'jav\' class=\'nav-item\'>");
document.writeln("              <a href=\'/index.php/vod/type/id/33.html\'>视频四区</a></li>");
document.writeln("");
document.writeln("   ");
document.writeln("         ");
document.writeln("");
document.writeln("            <li data-nav=\'jav\' class=\'nav-item\'>");
document.writeln("              <a href=\'/index.php/vod/type/id/34.html\'>视频五区</a></li>");
document.writeln("");
document.writeln("   ");
document.writeln("   ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("          </nav>");
document.writeln("        </ul>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("      </div>");
document.writeln("    </nav>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  </div>");
document.writeln("  <!----></header>");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("	.ui.icon.input>i.icon:not(.link){pointer-events: initial;}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <header id=\'pc_header\' class=\'header navbar-fixed-top\' >");
document.writeln("    <!---->");
document.writeln("    <nav id=\'desktop-header\' class=\'navbar navbar-default  navbar-custom\'>");
document.writeln("      <div class=\'container-fluid ui container \'>");
document.writeln("        <div class=\'up-bar\'>");
document.writeln("          <div class=\'navbar-header flex flex-center\'>");
document.writeln("            <a href=\'/\' class=\'application-name navbar-brand flex flex-centered\'>");
document.writeln("              <img src=\'/pp999/img/logo.gif\' title=\'ThePorn \' class=\'logo\'></a>");
document.writeln("            <ul class=\'nav navbar-nav navbar-over nav-text header-search mr10 search-box\'>");
document.writeln("              <li class=\'active\'>");
document.writeln("                <form action=\'/index.php/vod/search.html\' method=\'post\' id=\'search_form\' onsubmit=\'$g.on_search()\'>");
document.writeln("                  <div class=\'ui category search\'>");
document.writeln("                    <div class=\'ui icon input\'>");
document.writeln("                      <input type=\'search\' placeholder=\'搜索\' autocomplete=\'off\' id=\'ss\' name=\'wd\' class=\'prompt\'>");
document.writeln("                      <i class=\'search icon\' onclick=\'tj()\'></i>");
document.writeln("                    </div>");
document.writeln("                  </div>");
document.writeln("                </form>");
document.writeln("              </li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("      ");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("");
document.writeln("<script>");
document.writeln("	function tj(){");
document.writeln("		");
document.writeln("");
document.writeln("    window.location =\'/index.php/vod/search/wd/\'+$(\'#ss\').val()+\'.html\' ;");
document.writeln("");
document.writeln("");
document.writeln("	}");
document.writeln("");
document.writeln("</script>");
document.writeln("");
document.writeln("      <div class=\'desktop-menu-outer\'>");
document.writeln("        <div id=\'desktop-menu\' class=\'container-fluid ui container menu-container \'>");
document.writeln("          <div class=\'desktop-menu-inner cl\'>");
document.writeln("            <div class=\' navbar-collapse show collapse\'>");
document.writeln("              <ul data-nav=\'categories-all\' class=\'nav navbar-nav navbar-over nav-text\' style=\'margin-left: 0px;\'>");
document.writeln("                <li class=\'active\'>");
document.writeln("                  <a href=\'/\' data-nav=\'categories-all\'>主页</a></li>");
document.writeln("              </ul>");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<ul class=\'nav navbar-nav navbar-over nav-text\' data-nav=\'best-videos\'>");
document.writeln("    <li class=\'active\'>");
document.writeln("      <div class=\'ui live_sex right dropdown item dropdown-parent\'> <a href=\'/index.php/vod/type/id/30.html\'>视频一区</a>");
document.writeln("");
document.writeln("");
document.writeln("<i class=\'dropdown icon\' style=\'margin-left: 0px\'></i>");
document.writeln("        <div class=\'menu dropdown-menu\'>");
document.writeln("            <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/29.html\'>人兽性交</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/27.html\'>女同性恋</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/11.html\'>伦理影片</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/16.html\'>口交视频</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/17.html\'>自慰系列</a>");
document.writeln("          </div>");
document.writeln(" ");
document.writeln("        </div>");
document.writeln("");
document.writeln("");
document.writeln("        ");
document.writeln("");
document.writeln("      </div>");
document.writeln("    </li>");
document.writeln("  </ul>");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<ul class=\'nav navbar-nav navbar-over nav-text\' data-nav=\'best-videos\'>");
document.writeln("    <li class=\'active\'>");
document.writeln("      <div class=\'ui live_sex right dropdown item dropdown-parent\'> <a href=\'/index.php/vod/type/id/31.html\'>视频二区</a>");
document.writeln("");
document.writeln("");
document.writeln("<i class=\'dropdown icon\' style=\'margin-left: 0px\'></i>");
document.writeln("        <div class=\'menu dropdown-menu\'>");
document.writeln("            <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/1.html\'>日韩无码</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/6.html\'>人妻系列</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/10.html\'>自拍偷拍</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/12.html\'>AV明星</a>");
document.writeln("          </div>");
document.writeln(" ");
document.writeln("        </div>");
document.writeln("");
document.writeln("");
document.writeln("        ");
document.writeln("");
document.writeln("      </div>");
document.writeln("    </li>");
document.writeln("  </ul>");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<ul class=\'nav navbar-nav navbar-over nav-text\' data-nav=\'best-videos\'>");
document.writeln("    <li class=\'active\'>");
document.writeln("      <div class=\'ui live_sex right dropdown item dropdown-parent\'> <a href=\'/index.php/vod/type/id/32.html\'>视频三区</a>");
document.writeln("");
document.writeln("");
document.writeln("<i class=\'dropdown icon\' style=\'margin-left: 0px\'></i>");
document.writeln("        <div class=\'menu dropdown-menu\'>");
document.writeln("            <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/2.html\'>国产精品</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/9.html\'>动漫精品</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/13.html\'>3P合辑</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/14.html\'>巨乳系列</a>");
document.writeln("          </div>");
document.writeln(" ");
document.writeln("        </div>");
document.writeln("");
document.writeln("");
document.writeln("        ");
document.writeln("");
document.writeln("      </div>");
document.writeln("    </li>");
document.writeln("  </ul>");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<ul class=\'nav navbar-nav navbar-over nav-text\' data-nav=\'best-videos\'>");
document.writeln("    <li class=\'active\'>");
document.writeln("      <div class=\'ui live_sex right dropdown item dropdown-parent\'> <a href=\'/index.php/vod/type/id/33.html\'>视频四区</a>");
document.writeln("");
document.writeln("");
document.writeln("<i class=\'dropdown icon\' style=\'margin-left: 0px\'></i>");
document.writeln("        <div class=\'menu dropdown-menu\'>");
document.writeln("            <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/3.html\'>日韩精品</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/4.html\'>欧美精品</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/7.html\'>制服诱惑</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/20.html\'>教师学生</a>");
document.writeln("          </div>");
document.writeln(" ");
document.writeln("        </div>");
document.writeln("");
document.writeln("");
document.writeln("        ");
document.writeln("");
document.writeln("      </div>");
document.writeln("    </li>");
document.writeln("  </ul>");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<ul class=\'nav navbar-nav navbar-over nav-text\' data-nav=\'best-videos\'>");
document.writeln("    <li class=\'active\'>");
document.writeln("      <div class=\'ui live_sex right dropdown item dropdown-parent\'> <a href=\'/index.php/vod/type/id/34.html\'>视频五区</a>");
document.writeln("");
document.writeln("");
document.writeln("<i class=\'dropdown icon\' style=\'margin-left: 0px\'></i>");
document.writeln("        <div class=\'menu dropdown-menu\'>");
document.writeln("            <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/28.html\'>少女萝莉</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/5.html\'>中文字幕</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/8.html\'>强奸乱伦</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/15.html\'>颜射系列</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/18.html\'>SM重味</a>");
document.writeln("          </div>");
document.writeln("           <div class=\'item\'>");
document.writeln("            <a href=\'/index.php/vod/type/id/21.html\'>大秀视频</a>");
document.writeln("          </div>");
document.writeln(" ");
document.writeln("        </div>");
document.writeln("");
document.writeln("");
document.writeln("        ");
document.writeln("");
document.writeln("      </div>");
document.writeln("    </li>");
document.writeln("  </ul>");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("         ");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </nav>");
document.writeln("  </header>");
document.writeln("");
document.writeln("");
document.writeln("  <script>");
document.writeln("    // 等待文档加载完成后执行");
document.writeln("    $(document).ready(function() {");
document.writeln("");
document.writeln("      // 当鼠标移入或移出下拉菜单父元素时触发的事件");
document.writeln("      $(\'.dropdown-parent\').hover(");
document.writeln("        // 鼠标移入后展开下拉菜单");
document.writeln("        function() {");
document.writeln("          $(this).children(\'.dropdown-menu\').show();");
document.writeln("        },");
document.writeln("        // 鼠标移出后收起下拉菜单");
document.writeln("        function() {");
document.writeln("          $(this).children(\'.dropdown-menu\').hide();");
document.writeln("        }");
document.writeln("      );");
document.writeln("");
document.writeln("");
document.writeln("    });");
document.writeln("  </script>");