var sysConfig = {
  baseUrl: 'https://wap2.hispace.hicloud.com',
  domainUrl: 'https://appgallery5.huawei.com/',
  queryTimeout: 80000,
  serviceType: 20,
  pageSize: 15,
  externalLink: {
    userContract: 'https://privacy.consumer.huawei.com/legal/hiapp/terms.htm',
    privacyPolicy: 'https://privacy.consumer.huawei.com/legal/hiapp/privacy-statement.htm',
    aboutCookie: 'https://consumer.huawei.com/cn/legal/cookie-policy/',
    beian: ''
  },
  appIdOfAppGallery: "C27162",
  maxResults: 25,
  isOversea: true,
  validDomains:["https://appgallery1.huawei.com", "https://appgallery7.huawei.com", "https://appgallery8.huawei.com"],
  basePicture: 'this.style.background="#f2f2f2"',
  site: 'sg',
  mwIndexUrl: 'https://wap2.hispace.hicloud.com/uowap/index.html',
  mwAppDetailsUrl: 'https://appgallery.huawei.com/app/',
  HWClientDownloadUrl: 'https://appgallery.cloud.huawei.com/appdl/C27162',
  version: '10.4.1.300',
  contextPath: '',
  siteId: 'singapore',
  webEdge: {
    switch: 'ON',
    "baseUrl_north.china": 'https://web-drcn.hispace.dbankcloud.cn',
    "baseUrl_singapore": 'https://web-dra.hispace.dbankcloud.cn',
    "baseUrl_europe": 'https://web-dre.hispace.dbankcloud.cn',
    "baseUrl_russia": 'https://web-drru.hispace.dbankcloud.cn'
  },
  hotsearchKeyCount:10,
  resource: {
    fastAppScriptUrl: ''
  },
    hasdk: {
      reportUrl: 'https://metrics-dra.dt.hicloud.com:6447/webv1',
      idSite: 'AppGalleryDistWapFrontService',
      isImgMethod: '1',
      appDetailPageEventLabel: 'appdetailpage',
    },
  showInstallDialogDelayMs: 3000,
  learningDataProcessingUrl: 'https://privacy.consumer.huawei.com/legal/hiapp/privacy-statement.htm?country=CN&branchid=2&language=en_US',
  navIphoneDownUrl: 'https://appgallery.cloud.huawei.com/appdl/C27162?cno=portal',
  navWindowsDownUrl: 'https://appgallery.cloud.huawei.com/appdl/C499170478846388928?cno=portal',
  checkDeeplinkTimeout: 2500,
  changeNormalBtnSeat: true,
  branchId: '1',
  branchIds: '2',
  uaBrandMatchingRule:[{brandName:"honor",regExp:"\\bhonor|YOK-AN10|YOK-N49|KJR-W09|ALA-AN70|PMT-AN70|AGM3-AL09HN|AGM3-W09HN|HN55LOKS|HN65LOKS|KOB2-AL00HN|KOB2-W09HN|HJC-AN90|KAN-B39|Kanon-B39S|Kanon-B39P|Kanon-B39A|Kanon-B39H|NZA-AL00|KOZ-AL00|KOZ-AL40|NTH-AN00|NTH-NX9|RNA-AN00|RNA-TN00|JLH-AN00|AGM-W09HN|AGM-AL09HN|CHL-AN00|NTN-AN20|ELZ-AN00|ELZ-AN10|ELZ-AN20|CHL-AL00|BRT-W09|HJC-LX9|KRJ2-W09|KRJ2-AN00|HN43DNTA|HN55DNTA|HN65DNTA|BRT-AN09|NEW-AN90|TFY-AN00|KKG-AN70|CAH-AN00|IKD-LX9|HNC-AN00|HNC-AN10|HNC-AN20|BNF-AN00|ALG-AN00|ALG-TN00|BXX-AN09|TFY-AN40|CMA-AN00|CMA-AN40|LOK-350XS|LOK-360XS|LDR-AN00|TAL-AN00|TAL-TN00|ANY-AN00|LGE-AN00|LGE-AN10|LGE-AN20|LGE-AN60|LGE-AN61|MUS-B19S|MUS-B19P|MUS-B19D|GIA-AN00|YAL-AL10\\b"},{brandName:"huawei",regExp:"\\bHuawei\\b"},{brandName:"meizu",regExp:"\\bMZ\\b"}],
  appmarket:"com.huawei.appmarket",
  appdiscovery:"com.huawei.appdiscovery",
  applinkcfg:{appmarket:{cfg:{"agcgw":{"backurl":"connect-drcn.hispace.hicloud.com","url":"connect-drcn.dbankcloud.cn","websocketbackurl":"connect-ws-drcn.hispace.dbankcloud.com","websocketurl":"connect-ws-drcn.hispace.dbankcloud.cn"},"agcgw_all":{"CN":"connect-drcn.dbankcloud.cn","CN_back":"connect-drcn.hispace.hicloud.com","DE":"connect-dre.dbankcloud.cn","DE_back":"connect-dre.hispace.hicloud.com","RU":"connect-drru.dbankcloud.cn","RU_back":"connect-drru.hispace.hicloud.com","SG":"connect-dra.dbankcloud.cn","SG_back":"connect-dra.hispace.hicloud.com"},"client":{"cp_id":"260086000000068459","product_id":"9105163812218582324","client_id":"190382689382040640","client_secret":"D0C034E89EBD18278D7F103A32AFBCD913869A95C6494B9BED8198C39FBA0421","project_id":"9105163812218582324","app_id":"1027162","package_name":"com.huawei.appmarket"},"oauth_client":{"client_id":"1027162","client_type":1},"app_info":{"app_id":"1027162","package_name":"com.huawei.appmarket"},"service":{"analytics":{"collector_url":"datacollector-drcn.dt.hicloud.com,datacollector-drcn.dt.dbankcloud.cn","collector_url_ru":"datacollector-drru.dt.hicloud.com,datacollector-drru.dt.dbankcloud.cn","collector_url_sg":"datacollector-dra.dt.hicloud.com,datacollector-dra.dt.dbankcloud.cn","collector_url_de":"datacollector-dre.dt.hicloud.com,datacollector-dre.dt.dbankcloud.cn","collector_url_cn":"datacollector-drcn.dt.hicloud.com,datacollector-drcn.dt.dbankcloud.cn","resource_id":"p1","channel_id":""},"search":{"url":"https://search-drcn.cloud.huawei.com"},"cloudstorage":{"storage_url":"https://agc-storage-drcn.platform.dbankcloud.cn"},"ml":{"mlservice_url":"ml-api-drcn.ai.dbankcloud.com,ml-api-drcn.ai.dbankcloud.cn"}},"region":"CN","configuration_version":"3.0","appInfos":[{"package_name":"com.huawei.appmarket","client":{"app_id":"1027162"},"app_info":{"package_name":"com.huawei.appmarket","app_id":"1027162"},"oauth_client":{"client_type":1,"client_id":"1027162"}}]},prefixUrl:'https://appmarket03.dra.agconnect.link'},appmarket_discover:{cfg:{"agcgw":{"backurl":"connect-drcn.hispace.hicloud.com","url":"connect-drcn.dbankcloud.cn","websocketbackurl":"connect-ws-drcn.hispace.dbankcloud.com","websocketurl":"connect-ws-drcn.hispace.dbankcloud.cn"},"agcgw_all":{"CN":"connect-drcn.dbankcloud.cn","CN_back":"connect-drcn.hispace.hicloud.com","DE":"connect-dre.dbankcloud.cn","DE_back":"connect-dre.hispace.hicloud.com","RU":"connect-drru.dbankcloud.cn","RU_back":"connect-drru.hispace.hicloud.com","SG":"connect-dra.dbankcloud.cn","SG_back":"connect-dra.hispace.hicloud.com"},"client":{"cp_id":"260086000000068459","product_id":"9105163812218582324","client_id":"190382689382040640","client_secret":"D0C034E89EBD18278D7F103A32AFBCD913869A95C6494B9BED8198C39FBA0421","project_id":"9105163812218582324","app_id":"1027162","package_name":"com.huawei.appmarket"},"oauth_client":{"client_id":"1027162","client_type":1},"app_info":{"app_id":"1027162","package_name":"com.huawei.appmarket"},"service":{"analytics":{"collector_url":"datacollector-drcn.dt.hicloud.com,datacollector-drcn.dt.dbankcloud.cn","collector_url_ru":"datacollector-drru.dt.hicloud.com,datacollector-drru.dt.dbankcloud.cn","collector_url_sg":"datacollector-dra.dt.hicloud.com,datacollector-dra.dt.dbankcloud.cn","collector_url_de":"datacollector-dre.dt.hicloud.com,datacollector-dre.dt.dbankcloud.cn","collector_url_cn":"datacollector-drcn.dt.hicloud.com,datacollector-drcn.dt.dbankcloud.cn","resource_id":"p1","channel_id":""},"search":{"url":"https://search-drcn.cloud.huawei.com"},"cloudstorage":{"storage_url":"https://agc-storage-drcn.platform.dbankcloud.cn"},"ml":{"mlservice_url":"ml-api-drcn.ai.dbankcloud.com,ml-api-drcn.ai.dbankcloud.cn"}},"region":"CN","configuration_version":"3.0","appInfos":[{"package_name":"com.huawei.appmarket","client":{"app_id":"1027162"},"app_info":{"package_name":"com.huawei.appmarket","app_id":"1027162"},"oauth_client":{"client_type":1,"client_id":"1027162"}}]},prefixUrl:'https://appmarket03.dra.agconnect.link'}},
  installVersionSwitch:true,
  pkgNameWhiteList:[{packageName:'com.huawei.apptouch.zgallery',appName:'ZGallery'},{packageName:'com.huawei.apptouch.etstore',appName:'Ethiotel App Store'},{packageName:'com.xrom.intl.appcenter',appName:'M Store'},{packageName:'com.huawei.apptouch.appcell',appName:'AppCell'},{packageName:'com.huawei.apptouch.waktiplay',appName:'AppTouch'},{packageName:'com.huawei.gamebox.global',appName:'KGallery'},{packageName:'com.huawei.apptouch.kgallery',appName:'KGallery'},{packageName:'com.huawei.apptouch.laosetl',appName:'LaosETL'},{packageName:'com.huawei.apptouch.aruplus',appName:'AppTouch'}],
  showPermissions:false,
  isShowHWbtn:'0',
  channelPackageNameMapping:[{keyWord:'Firefox',packageName:'org.mozilla.firefox'},{keyWord:'UWS',packageName:'com.UCMobile'},{keyWord:'MQQBrowser',packageName:'com.tencent.mtt'},{keyWord:'HuaweiBrowser',packageName:'com.huawei.browser'},{keyWord:'VivoBrowser',packageName:'com.vivo.browser'},{keyWord:'HeyTapBrowser',packageName:'com.heytap.browser'},{keyWord:'Aphone Browser',packageName:'com.qihoo.browser'},{keyWord:'SougouMSE',packageName:'sogou.mobile.explorer'},{keyWord:'NewsArticle',packageName:'com.cat.readall'},{keyWord:'Quark',packageName:'com.quark.browser'},{keyWord:'UCBrowser',packageName:'com.UCMobile'},{keyWord:'YaBrowser',packageName:'com.yandex.browser'},{keyWord:'DuckDuckGo',packageName:'com.duckduckgo.mobile.android'},{keyWord:'SamsungBrowser',packageName:'com.sec.android.app.sbrowser'},{keyWord:'PHX',packageName:'com.transsion.phoenix'},{keyWord:'EdgA',packageName:'com.microsoft.emmx'},{keyWord:'baiduboxapp',packageName:'com.baidu.browser.apps'},{keyWord:'minibrowser',packageName:'com.jx.minibrowser'},{keyWord:'haowangzhi;privatebrowser',packageName:'com.jx.privatebrowser'},{keyWord:'haowangzhi;ebrowser',packageName:'com.ledu.ebrowser'},{keyWord:'uabrowser',packageName:'com.sljh.uabrowser'},{keyWord:'hao123',packageName:'com.baidu.hao123'},{keyWord:'packagename',packageName:'com.yczj.mybrowser'},{keyWord:'OPR',packageName:'com.oupeng.mini.android'},{keyWord:'yisou',packageName:'com.browser.yisou'},{keyWord:'XiaoMi/MiuiBrowser',packageName:'com.qingliu.browser.Pi'},{keyWord:'Tomato Browser',packageName:'com.yotu.video'},{keyWord:'CYBrowser',packageName:'com.szcx.browser'},{keyWord:'agentweb',packageName:'com.ly.mengjia.browser'},{keyWord:'Mb2345Browser',packageName:'com.browser2345'}],
  detailType_AGDAPI:5,
  excludeUrlParam_AGDAPI:['callType','shareFrom'],
  partnerId:'unKnow',
  debugMode:false,
  appStoreDelayTime:1000,
  qqMatcherRegExp: /QQTheme/i,
  interfaceCodeSwitch: 'on'
};
