var annoucements={showAnnoucements:function(){},close:function(a){$(".close--annoucement").click(function(){$(".announcement-panel").slideUp(200)})},carousel:function(){$(".annoucement--shoutout").slick({adaptiveHeight:!0,fade:!0})},init:function(){this.carousel();this.showAnnoucements();this.close()}};
$(function(){0<$("#ticker_src").length&&$.ajax({url:$("#ticker_src").val(),type:"GET",dataType:"jsonp",jsonp:"callback",jsonpCallback:"homeTheBigStory",success:function(a){var b=!0;a.emergencyTickerTexts&&a.emergencyTickerTexts.toString()&&""!=a.emergencyTickerTexts.toString()&&(b=!1,$(".annoucement--shoutout").html("\x3cdiv class\x3d\"shoutout\"\x3e\x3cimg src\x3d'/content/dam/onemotoring/img/corp/ticker_msg.png' style\x3d'vertical-align: middle;display: initial;'\x3e\x26nbsp;\x26nbsp;"+a.emergencyTickerTexts.toString()+
"\x3c/div\x3e"),$(".announcement-panel").show());b&&a.tickerTexts&&a.tickerTexts.length&&0<a.tickerTexts.length&&0<a.tickerTexts[0].length&&(coeHtml=a.tickerTexts,0<$("#coeDetails").length&&$("#coeDetails").html(coeHtml));annoucements.init()}})});function tickerClose(){$(".announcement-panel").hide();$(".ticker-angel-button").show()}function tickerOpen(){$(".announcement-panel").show();$(".ticker-angel-button").hide()}
$(document).ready(function(){$.ajax({url:$("#coe_source_path").val(),type:"GET",dataType:"jsonp",jsonp:"callback",jsonpCallback:"homeCoePrices",success:function(a){if(a.biddingStatus){if(a.abortDate)var b='\x3cdiv class\x3d"coe-updates__desc"\x3e'+a.biddingStatus+"aborted on "+a.abortDate+"\x3c/div\x3e";else{b='\x3cdiv class\x3d"coe-updates__desc"\x3e'+a.biddingStatus+"\x3c/div\x3e";b+='\x3ctable class\x3d"coe-updates__pricing-table" width\x3d"100%"\x3e';var c=["A","B","C","D","E"];for(i=0;i<c.length;i++){var d=
"category"+c[i];b+="\x3ctr\x3e";b+="\x3cth\x3eCat "+c[i]+"\x3c/th\x3e";b+='\x3ctd class\x3d"coe-updates__type"\x3e\x3cimg src\x3d"/content/dam/onemotoring/img/coe/coe_cat_'+c[i].toLowerCase()+'.png" alt\x3d"COE Cat '+c[i]+'"\x3e\x3c/td\x3e';b+='\x3ctd class\x3d"coe-updates__price"\x3e'+parseFloat(a[d].quotaPremium,10).toFixed(0).replace(/(\d)(?=(\d{3})+(?!\d))/g,"$1,").toString()+"\x3c/td\x3e";0==a[d].qpChangeIndicator?(b+='\x3ctd class\x3d"coe-updates__indicator coe-updates__indicator--dec"\x3e',
b+='\x3ci class\x3d"fa fa-caret-down" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/td\x3e'):2==a[d].qpChangeIndicator?(b+='\x3ctd class\x3d"coe-updates__indicator coe-updates__indicator--inc"\x3e',b+='\x3ci class\x3d"fa fa-caret-up" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/td\x3e'):(b+='\x3ctd class\x3d"coe-updates__indicator coe-updates__indicator--same"\x3e',b+='\x3ci class\x3d"fa fa-minus" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/td\x3e');b+="\x3c/tr\x3e"}b+="\x3c/table\x3e"}$("#coe-updates-content").html(b)}else a=
'\x3cdiv class\x3d"coe-updates__desc clearfix"\x3e\x3cdiv class\x3d"col-sm-12 col-md-3 align-center-md-down"\x3e\x3cimg alt\x3d"COE Cat" src\x3d"/content/dam/onemotoring/img/coe/icon-bidding.png"\x3e\x3c/div\x3e\x3cdiv class\x3d"bidding__body col-sm-12 col-md-9 align-center-md-down"\x3eLIVE BIDDING\x3cp id\x3d"coeDetails"\x3e'+coeHtml,a+='\x3c/p\x3e\x3c/div\x3e\x3c/div\x3e\x3cbr\x3e\x3cdiv class\x3d"align-center-md-down"\x3e\x3ca rel\x3d"noreferrer" href\x3d"https://ocoe.lta.gov.sg" class\x3d"btn"\x3eEnquire/Revise your bid\x3ci class\x3d"fa fa-arrow-right" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/a\x3e\x3c/div\x3e',
$("#coe-updates-content").html(a),$("#normal_coe").hide(),$("#live_coe").show()}})});var monthNames="JAN FEB MAR APR MAY JUN JUL AUG SEP OCT NOV DEC".split(" ");function formatDt(a){return 10>parseInt(a)?"0"+a.toString():a}function formatTime(a){var b=formatDt(a.getHours())+":"+formatDt(a.getMinutes());return b=12<=a.getHours()?b+" PM":b+" AM"}
function getTimeDiff(a){var b=new Date-a;a=Math.floor(b/1E3/60/60);b-=36E5*a;var c=Math.floor(b/1E3/60);b=Math.floor((b-6E4*c)/1E3);return 0<a?"updated "+(1==a?a+" hr":a+" hrs")+" ago":0<c?"updated "+(1==c?c+" min":c+" mins")+" ago":0<b?"updated "+(1==c?c+" sec":c+" secs")+" ago":"now"}$(document).ready(function(){getHomeTrafficCamera()});
function getHomeTrafficCamera(){$.ajax({url:$("#cam_source_path").val(),type:"GET",dataType:"jsonp",jsonp:"callback",jsonpCallback:"homeTrafficCamera",success:function(a){if(a.imageUrl){var b="",c=a.imageUrl2;-1!=a.imageUrl2.indexOf("nocameraimage.jpg")&&(c="/content/dam/onemotoring/images/nocamera.jpg");var d=new Date(a.imageDateTime2),e=Number(d.getMonth())+1;e=formatDt(d.getDate())+"/"+formatDt(e)+"/"+d.getFullYear()+" "+formatTime(d);b=b+'\x3cdiv class\x3d"card__title"\x3eView from Tuas Checkpoint\x3c/div\x3e\x3cdiv class\x3d"timestamp"\x3e\x3cspan class\x3d"left"\x3e'+
(e+"\x3c/span\x3e")+('\x3cspan class\x3d"right"\x3e'+getTimeDiff(d)+"\x3c/span\x3e");b=b+'\x3c/div\x3e\x3cdiv class\x3d"camera-feed"\x3e'+('\x3cimg src\x3d"'+c+'" alt\x3d"Tuas Checkpoint"\x3e')+"\x3c/div\x3e";$("#tuas_camera").html(b);c=a.imageUrl;-1!=a.imageUrl.indexOf("nocameraimage.jpg")&&(c="/content/dam/onemotoring/images/nocamera.jpg");a=new Date(a.imageDateTime);b=Number(a.getMonth())+1;b=formatDt(a.getDate())+"/"+formatDt(b)+"/"+a.getFullYear()+" "+formatTime(a);b='\x3cdiv class\x3d"card__title"\x3eView from Woodlands Checkpoint (Towards Johor)\x3c/div\x3e\x3cdiv class\x3d"timestamp"\x3e\x3cspan class\x3d"left"\x3e'+
(b+"\x3c/span\x3e");b+='\x3cspan class\x3d"right"\x3e'+getTimeDiff(a)+"\x3c/span\x3e";b+="\x3c/div\x3e";b+='\x3cdiv class\x3d"camera-feed"\x3e';b+='\x3cimg src\x3d"'+c+'" alt\x3d"Woodlands Checkpoint"\x3e';b+="\x3c/div\x3e";$("#woodlands_camera").html(b)}}})}
$(document).ready(function(){$.ajax({url:$("#traffic_news_source_path").val(),type:"GET",dataType:"jsonp",jsonp:"callback",jsonpCallback:"homeTrafficIncident",success:function(a){if(a.trafficNews&&0<a.trafficNews.length){a=a.trafficNews;for(var b='\x3ctable class\x3d"traffic-updates__table" width\x3d"100%"\x3e',c=0;c<a.length;c++){var d=a[c],e="\x3ctr\x3e";e+='\x3ctd class\x3d"traffic-updates__type"\x3e';e+='\x3cimg src\x3d"/content/dam/onemotoring/img/traffic_news/traffic_'+d.typeId+'.png" alt\x3d"Traffic News Icon"\x3e';
e+="\x3c/td\x3e\x3ctd\x3e";e+='\x3cdiv class\x3d"traffic-updates__desc"\x3e'+d.newsText+"\x3c/div\x3e";e+='\x3cdiv class\x3d"traffic-updates__time"\x3e'+d.date+" "+d.time+"\x3c/div\x3e";e+="\x3c/td\x3e";e+="\x3c/tr\x3e";b+=e}b+="\x3c/table\x3e";$("#traffic-updates-content").html(b)}else $("#traffic-updates-content").html("Currently there is no traffic news update.")}});$("#tc_search").on("click",function(a){a=$("#traffic_search").val();var b=$("#traffic_news_page_path").val();document.location.href=
b+"?type\x3dtc\x26searchText\x3d"+a})});