"use strict";
var IndeedQuiz={expire_time:0,submited_value:"",do_decode:"",quiz_id:0,question_id:0,submit_quiz_button:"",next_bttn:"",course_id:0,start:function(){jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_start_quiz",qid:this.quiz_id,course_id:this.course_id},success:function(a){window.location.href=a}})},shift:function(a){jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_quiz_shift_question",question_id:this.question_id,
qid:this.quiz_id,direction:a,course_id:this.course_id},success:function(b){window.location.href=b}})},saveAnswer:function(a){var b="[name="+this.question_id+"]",c=jQuery(b).attr("type"),e=0;"undefined"==typeof c&&(c=jQuery("[name='"+this.question_id+"[]']").attr("data-field_type"),"sorting"==c?c="sorting":"fill_in"==c?c="fill_in":"matching"==c?c="matching":"textarea"==c?c="textarea":(c=jQuery("[name='"+this.question_id+"']").attr("data-field_type"),c="textarea"==c?"textarea":"checkbox"));var h={action:"ulp_save_question_answer",
question_id:this.question_id,qid:this.quiz_id,course_id:this.course_id};switch(c){case "radio":var f=jQuery(b+":checked").val();break;case "text":case "number":case "hidden":case "textarea":f=jQuery(b).val();break;case "sorting":var k=[];jQuery("[name='"+this.question_id+"[]']").each(function(){k.push(jQuery(this).val())});f=JSON.stringify(k);e=1;break;case "checkbox":k=[];jQuery("[name='"+this.question_id+"[]']").each(function(){jQuery(this).is(":checked")&&k.push(jQuery(this).val())});f=JSON.stringify(k);
e=1;break;case "fill_in":k=[];jQuery("[name='"+this.question_id+"[]']").each(function(){k.push(jQuery(this).val())});f=JSON.stringify(k);e=1;break;case "matching":k=[];jQuery("[name='"+this.question_id+"[]']").each(function(){k.push(jQuery(this).val())});f=JSON.stringify(k);var l=[];jQuery(".js-ulp-micro-question").each(function(){l.push(jQuery(this).html())});h.the_questions=l;e=1}h.the_value=f;h.decode=e;jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:h,
success:function(r){1==a&&IndeedQuiz.submit()}})},makeDisabled:function(){jQuery("[name="+this.question_id+"]").attr("disabled","disabled")},returnCorrectOrWrong:function(){var a='<div class="ulp-correct-answer-msg">'+this.correct_answer_msg+"</div>",b='<div class="ulp-wrong-answer-msg">'+this.wrong_answer_msg+"</div>";jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_question_return_correct_or_wrong",question_id:this.question_id,qid:this.quiz_id,
course_id:this.course_id},success:function(c){1==c?jQuery(".ulp-question-responses").append(a):jQuery(".ulp-question-responses").append(b);1!=IndeedQuiz.is_last()&&IndeedQuiz.insert_next()}})},submit:function(){jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_submit_quiz",qid:this.quiz_id,course_id:this.course_id},success:function(a){window.location.href=a}})},is_last:function(){return this.is_last_question},insert_submit:function(){jQuery(".ulp-question-buttons-wrapper").append('<div class="ulp-quiz-submit-via-ajax" id="ulp_quiz_submit_via_ajax">'+
this.submit_quiz_button+"</div>")},insert_next:function(){jQuery(".ulp-question-buttons-wrapper").append('<div class="ulp-quiz-next-button" id="ulp_quiz_next_question">'+this.next_bttn+"</div>")}},IndeedCourse={enroll:function(a){jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_do_enroll_course",course_id:a},success:function(b){jQuery("#enroll_course_"+a).remove();jQuery("#ulp_enroll_box_course_"+a).append(b);setTimeout(function(){location.reload()},
2E3)}})},finish:function(){var a=jQuery("#ulp_finish_course_bttn").attr("data-course_id");jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_finish_course",course_id:a},success:function(b){location.reload()}})},retake:function(a){jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_do_retake_course",course_id:a},success:function(b){jQuery("#ulp_retake_box_message_"+a).append(b);setTimeout(function(){location.reload()},
6E3)}})}},IndeedLesson={doComplete:function(){var a=jQuery("#ulp_lesson_complete_bttn").attr("data-lesson_id");jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_complete_lesson",lesson_id:a},success:function(b){1==b&&location.reload()}})}},IndeedQuestion={showHint:function(){"ulp-hint-hide"==jQuery("#ulp_the_hint").attr("class")?jQuery("#ulp_the_hint").attr("class","ulp-hint-show"):jQuery("#ulp_the_hint").attr("class","ulp-hint-hide")}},UltimateLearningPro=
{current_page:null,init:function(){var a="object"==typeof ulp_messages?ulp_messages:JSON.parse(ulp_messages);jQuery("#ulp_start_quiz_bttn").on("click",function(){IndeedQuiz.start()});jQuery("#ulp_retake_quiz_bttn").on("click",function(){IndeedQuiz.start()});jQuery(document).on("click","#ulp_quiz_next_question",function(){IndeedQuiz.saveAnswer(!1);IndeedQuiz.shift("forward")});jQuery(document).on("click","#ulp_quiz_prev_question",function(){IndeedQuiz.saveAnswer(!1);IndeedQuiz.shift("back")});jQuery(document).on("click",
"#ulp_submit_quiz_bttn",function(){IndeedQuiz.saveAnswer(!0)});jQuery("#ulp_quiz_submit_via_ajax").on("click",function(){IndeedQuiz.saveAnswer(!1);IndeedQuiz.makeDisabled();jQuery("#ulp_quiz_submit_via_ajax").remove();jQuery("#ulp_hint_link").remove();setTimeout(function(){IndeedQuiz.returnCorrectOrWrong()},1E3)});jQuery("#ulp_hint_link").on("click",function(){IndeedQuestion.showHint()});jQuery("#ulp_become_instructor").on("click",function(){jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+
"/wp-admin/admin-ajax.php",data:{action:"ulp_become_instructor_ajax"},success:function(b){jQuery("#ulp_become_instructor").remove();jQuery(".ulp-become-instructor-wrapp").append(window.become_instructor_message);location.reload()}})});jQuery("#ulp_finish_course_bttn").on("click",function(){IndeedCourse.finish()});jQuery(".ulp-enroll-course-the-button").on("click",function(){var b=jQuery(this).attr("data-cid");IndeedCourse.enroll(b)});jQuery("#ulp_retake_course_bttn").on("click",function(){var b=jQuery(this).attr("data-course_id");
IndeedCourse.retake(b)});jQuery("#ulp_lesson_complete_bttn").on("click",function(){IndeedLesson.doComplete()});jQuery(".ulp-star-item .fa-ulp").on("hover",function(b){b=jQuery(this).parent().parent().attr("class");ulpUnsetStars(b);var c=jQuery(this).parent().attr("data-star_num");ulpSetStar(b,c)});jQuery(".ulp-star-item .fa-ulp").on("mouseout",function(b){b=jQuery(this).parent().parent().attr("class");ulpUnsetStars(b);jQuery(".js-ulp-course-rating").val()&&ulpSetStar(b,jQuery(".js-ulp-course-rating").val())});
jQuery(".ulp-star-item .fa-ulp").on("click",function(b){b=jQuery(this).parent().parent().attr("class");var c=jQuery(this).parent().attr("data-star_num");ulpSetStar(b,c);jQuery(".js-ulp-course-rating").val(c);return!1});jQuery("#note_course_id").on("click",ulpNoteOpenPopup);jQuery(".js-ulp-pay-course-bttn").on("click",function(){var b=jQuery(this).attr("data-course_id"),c=jQuery(this).attr("data-payment_type");jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_buy_course_via_standard_bttn",
course_id:b,payment_type:c},success:function(e){0==e||"0"==e?swal({title:a.error,text:a.general_error,type:"error",showCancelButton:!1,confirmButtonClass:"ulp-btn-danger",confirmButtonText:"Ok",closeOnConfirm:!0}):window.location.href=e}})});jQuery("#ulp_checkout").on("submit",function(){return"undefined"==typeof jQuery("[name=payment_type]:checked").val()?(swal({title:a.error,text:a.payment_type_error,type:"error",showCancelButton:!1,confirmButtonClass:"ulp-btn-danger",confirmButtonText:"Ok",closeOnConfirm:!0}),
!1):!0})}};function ulpSetStar(a,b){for(var c=1;c<=b;c++)jQuery("."+a+" .i_"+c+" .fa-ulp").removeClass("fa-star-o-ulp").addClass("fa-star-ulp")}function ulpUnsetStars(a){for(var b=1;6>b;b++)jQuery("."+a+" .i_"+b+" .fa-ulp").removeClass("fa-star-ulp").addClass("fa-star-o-ulp")}jQuery(function(){UltimateLearningPro.init()});
function ulpNoteOpenPopup(){jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_get_note_popup"},success:function(a){jQuery("body").append(a)}})}function ulpOpenInvoice(a){jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_get_invoice_popup",order_id:a},success:function(b){jQuery("body").append(b)}})}
function ulpClosePopup(){jQuery("#ulp_popup").fadeOut(500,function(){jQuery(this).remove()})}function ulpNoteSave(){jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_save_note",course_id:jQuery("#note_course_id").attr("data-course_id"),title:jQuery("#note_title").val(),content:jQuery("#note_content").val()},success:function(a){ulpClosePopup()}})}
function ulpLoveCourse(a,b){var c=jQuery("#"+b).attr("data-action"),e="add"==c?"ulp_add_to_watch_list":"ulp_remove_from_watch_list";jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:e,course_id:a},success:function(h){"add"==c?(jQuery("#"+b).attr("class",""),jQuery("#"+b).attr("class","ulp-watch-list-button ulp-watch-list-active"),jQuery("#wishlist-icon").attr("class",""),jQuery("#wishlist-icon").attr("class","fa-ulp fa-watch_list-ulp"),jQuery("#"+
b).attr("data-action","remove")):(jQuery("#"+b).attr("class",""),jQuery("#"+b).attr("class","ulp-watch-list-button ulp-watch-list-noactive"),jQuery("#wishlist-icon").attr("class",""),jQuery("#wishlist-icon").attr("class","fa-ulp fa-watch_list_not_assign-ulp"),jQuery("#"+b).attr("data-action","add"))}})}
function ulpRemoveFromWatchList(a){jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_remove_from_watch_list",course_id:jQuery(a.target).attr("data-course_id")},success:function(){course_id=jQuery(a.target).attr("data-course_id");jQuery(".ulp-remove-"+course_id).remove()}})}
function ulpRemoveNote(a){jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_delete_note",id:jQuery(a.target).attr("data-id")},success:function(b){jQuery(a.target).parent().remove()}})}jQuery(document).on("ready",function(){jQuery(".js-remove-watch-list").on("click",ulpRemoveFromWatchList,this.element);jQuery(".js-ulp-remove-note").on("click",ulpRemoveNote,this.element);jQuery("#ulp_checkout_payment_select input").on("click",ulpPaymentSelect,this.element)});
function ulpOpenCertificate(a){jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_get_certificate_popup",user_certificate_id:a},success:function(b){jQuery("body").append(b)}})}
function ulpPaymentSelect(a){jQuery("#js_ulp_checkout_loading_gif").css("visibility","visible");"stripe"==jQuery(a.target).val()?jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_get_stripe_payment_form"},success:function(b){0==jQuery("#ulp_stripe_payment_form_fields").length?(jQuery(a.target).parent().append(b),jQuery("#ulp_stripe_payment_form_fields").slideDown(500,function(){jQuery("#js_ulp_checkout_loading_gif").css("visibility","hidden")})):
jQuery("#js_ulp_checkout_loading_gif").css("visibility","hidden")}}):jQuery("#ulp_stripe_payment_form_fields").length?jQuery("#ulp_stripe_payment_form_fields").slideUp(500,function(){jQuery("#ulp_stripe_payment_form_fields").remove();jQuery("#js_ulp_checkout_loading_gif").css("visibility","hidden")}):jQuery("#js_ulp_checkout_loading_gif").css("visibility","hidden")}
function ulpDeleteFileViaAjax(a,b,c,e,h){if(confirm("Are you sure you want to delete?")){var f=jQuery(c).attr("data-h");jQuery.ajax({type:"post",url:decodeURI(window.ulp_site_url)+"/wp-admin/admin-ajax.php",data:{action:"ulp_delete_attachment_ajax_action",attachemnt_id:a,user_id:b,field_name:e,h:f},success:function(k){jQuery(h).val("");jQuery(c+" .ajax-file-upload-filename").remove();jQuery(c+" .ulp-delete-attachment-bttn").remove();jQuery(c+" .ulp-member-photo").length&&(jQuery(c+" .ulp-member-photo").remove(),
"ulp_avatar"==e&&(jQuery(c).prepend("<div class='ulp-no-avatar ulp-member-photo'></div>"),jQuery(c+" .ulp-file-upload").css("display","block")));jQuery(c+" .ulp-file-name-uploaded").length&&jQuery(c+" .ulp-file-name-uploaded").remove();jQuery(c+" .ajax-file-upload-progress").length&&jQuery(c+" .ajax-file-upload-progress").remove();jQuery(c+" .ulp-icon-file-type").length&&jQuery(c+" .ulp-icon-file-type").remove()}})}}
function ulpCheckAndH(a,b){jQuery(a).is(":checked")?jQuery(b).val(1):jQuery(b).val(0)}function ulpShowSelectorIf(a,b,c){b==c?jQuery(a).css("display","block"):jQuery(a).css("display","none")}
function ulpDoModuleToggle(a){var b="object"==typeof ulp_messages?ulp_messages:JSON.parse(ulp_messages);"none"==jQuery("#ulp_module_content_inside_"+a).css("display")?(jQuery("#ulp_module_content_inside_"+a).slideDown(500),b='<i class="fa-ulp fa-toggle_up-ulp" title="'+b.toggle_section+'" ></i>'):(jQuery("#ulp_module_content_inside_"+a).slideUp(500),b='<i class="fa-ulp fa-toggle_down-ulp" title="'+b.toggle_section+'" ></i>');jQuery("#ulp_toggle_modukle_"+a).html(b)}
function ulpAddZero(a){10>a&&(a="0"+a);return a}function openMediaUp(a,b){if(!c){var c=wp.media.frames.file_frame=wp.media({title:"Choose Image",button:{text:"Choose Image"},multiple:!1});c.on("select",function(){attachment=c.state().get("selection").first().toJSON();jQuery(a).val(attachment.url);""!=b&&(jQuery(b).attr("src",attachment.url),jQuery(b).css("display","block"))})}c.open()}function ulpInitPrinthis(a){"undefined"!=typeof window.printhisopt&&jQuery(a).printThis(window.printhisopt)}
jQuery(document).on("ready",function(){if(0<jQuery(".ulp-js-init-print-this").length){var a=jQuery(".ulp-js-init-print-this").attr("data-load_css");window.printhisopt={importCSS:!0,importStyle:!0,loadCSS:a,debug:!1,printContainer:!0,pageTitle:"",removeInline:!1,printDelay:333,header:null,formValues:!1}}0<jQuery(".ulp-js-quizes-special-settings").length&&(a=jQuery(this).attr("data-quiz_grade_type"),ulpShowSelectorIf("#ulp_point_description",a,"point"));0<jQuery(".ulp-js-add-edit-include-ckeditor").length&&
(jQuery(".ulp-js-add-edit-include-ckeditor").attr("data-base_path"),CKEDITOR.replace("post_content"));0<jQuery(".ulp-js-include-ckeditor-comming-soon-message").length&&(jQuery(".ulp-js-include-ckeditor-comming-soon-message").attr("data-base_path"),CKEDITOR.replace("ulp_course_coming_soon_message"));0<jQuery(".ulp-js-become-instructor-message").length&&(a=jQuery(".ulp-js-become-instructor-message").attr("data-value"),window.become_instructor_message='<div class="ulp-instructor-pending-request">'+a+
"</div>");if(jQuery(".ulp-js-form-field-micro-answer").length&&"undefined"!=typeof UlpFormFieldMatching){a=jQuery(".ulp-js-form-field-micro-answer").attr("data-title");var b=jQuery(".ulp-js-form-field-micro-answer").attr("data-message");UlpFormFieldMatching.init({droppableClass:".ulp-micro-answer",draggableClass:".ulp-item",possibleAnswersWrapp:".ulp-micro-answers-possible",standardTitleMessage:a,extraTitleMessage:b})}if(jQuery(".ulp-js-form-field-image-single-choice").length&&"undefined"!=typeof UlpFormFieldSingleChoice){var c=
jQuery(".ulp-js-form-field-image-single-choice").attr("data-name");UlpFormFieldSingleChoice.init({wrapper:".ulp-images-single-choice-wrapp .ulp-images-single-choice-one-item",name:c,selectedClass:"selected"})}jQuery(".ulp-datetime").length&&jQuery(".ulp-datetime").each(function(){jQuery(this).datepicker({dateFormat:"yy-mm-dd ",onSelect:function(d){var g=new Date;d=d+g.getHours()+":"+ulpAddZero(g.getMinutes())+":"+ulpAddZero(g.getSeconds());jQuery(this).val(d)}})});0<jQuery(".ulp-js-instructor-courses-special-settings").length&&
(a=jQuery(".ulp-js-instructor-courses-special-settings").attr("data-ulp_course_assessments"),b=jQuery(".ulp-js-instructor-courses-special-settings").attr("data-ulp_course_payment"),ulpShowSelectorIf("#ulp_zuiq_average",a,"quizes"),ulpShowSelectorIf("#ulp_course_price_num",b,1));jQuery("#ulp_drip_start_certain_date").length&&(jQuery("#ulp_drip_start_certain_date").datepicker({dateFormat:"dd-mm-yy",onClose:function(d){jQuery("#ihc_drip_end_certain_date").datepicker("option","minDate",d)}}),ulpShowSelectorIf("#after_x_time",
jQuery(".ulp-js-instructor-lesson-drip-content").attr("data-start_type"),1),ulpShowSelectorIf("#specific_date",jQuery(".ulp-js-instructor-lesson-drip-content").attr("data-start_type"),2));if(jQuery(".ulp-js-file-upload-settings").length){var e=jQuery(".ulp-js-file-upload-settings").attr("data-rand");a=jQuery(".ulp-js-file-upload-settings").attr("data-url");jQuery("#ulp_fileuploader_wrapp_"+e+" .ulp-file-upload").uploadFile({onSelect:function(d){jQuery("#ulp_fileuploader_wrapp_"+e+" .ajax-file-upload-container").css("display",
"block");return""!=jQuery("#ulp_upload_hidden_"+e).val()?(alert("To add a new image please remove the previous one!"),!1):!0},url:a,allowedTypes:"jpg,png,jpeg,gif",fileName:"avatar",dragDrop:!1,showFileCounter:!1,showProgress:!0,onSuccess:function(d,g,m,n){g&&(d=jQuery.parseJSON(g),"undefined"!=typeof d.secret&&jQuery("#ulp_fileuploader_wrapp_"+e).attr("data-h",d.secret),jQuery("#ulp_upload_hidden_"+e).val(d.id),g='<div onClick="ulpDeleteFileViaAjax('+d.id+", -1, '#ulp_fileuploader_wrapp_"+e+"', '' . 'ulp_avatar' . '', '#ulp_upload_hidden_"+
e+"');\" class='ulp-delete-attachment-bttn'>Remove</div>",jQuery("#ulp_fileuploader_wrapp_"+e+" .ulp-file-upload").prepend(g),jQuery("#ulp_fileuploader_wrapp_"+e+" .ulp-file-upload").prepend("<img src="+d.url+" class='ulp-member-photo' /><div class='ulp-clear'></div>"),jQuery(".ulp-no-avatar").remove(),setTimeout(function(){jQuery("#ulp_fileuploader_wrapp_"+e+" .ajax-file-upload-container").css("display","none")},3E3))}})}0<jQuery(".ulp-js-course-curriculum-slider").length&&(a=document.querySelector(".scroll-wrapper"),
new PerfectScrollbar(a));0<jQuery(".ulp-js-course-review-list-init").length&&"undefined"!=typeof UlpReviews&&(a=jQuery(".ulp-js-course-review-list-init").attr("data-slug"),b=jQuery(".ulp-js-course-review-list-init").attr("data-hash"),UlpReviews.init({offset:10,slug:a,hash:b,wrapper:".ulp-course-review-list"}));0<jQuery(".ulp-js-instructor-listing-comments").length&&CKEDITOR.replace("add_new_comment");0<jQuery(".ulp-js-instructor-questions-answers").length&&jQuery("#ulpsrotingtype_wrapp").sortable({update:function(d,
g){jQuery("#ulpsrotingtype_wrapp div").each(function(m,n){})}});if(0<jQuery(".ulp-js-lesson-complete-bttn").length){var h=jQuery(".ulp-js-lesson-complete-bttn").attr("data-seconds_remain"),f=new Timer;h=parseInt(h);f.start({countdown:!0,startValues:{seconds:h}});f.addEventListener("secondsUpdated",function(d){d=["minutes","seconds"];var g=h;3600<g&&(d=["hours","minutes","seconds"]);86400<g&&(d=["days","hours","minutes","seconds"]);jQuery("#ulp_lesson_countdown").html(f.getTimeValues().toString(d))});
f.addEventListener("targetAchieved",function(d){IndeedLesson.doComplete()})}0<jQuery(".ulp-js-the-countdown").length&&(h=jQuery(".ulp-js-the-countdown").attr("data-seconds_remain"),f=new Timer,h=parseInt(h),f.start({countdown:!0,startValues:{seconds:h}}),f.addEventListener("secondsUpdated",function(d){d=["minutes","seconds"];var g=h;3600<g&&(d=["hours","minutes","seconds"]);86400<g&&(d=["days","hours","minutes","seconds"]);jQuery("#ulp_quiz_countdown").html(f.getTimeValues().toString(d))}),f.addEventListener("targetAchieved",
function(d){IndeedQuiz.saveAnswer(!0)}));0<jQuery(".ulp-js-retake-bttn").length&&(a=jQuery(".ulp-js-retake-bttn").attr("data-quiz_id"),b=jQuery(".ulp-js-retake-bttn").attr("data-course_id"),IndeedQuiz.quiz_id=a,IndeedQuiz.course_id=b);0<jQuery(".ulp-js-quiz-start-bttn").length&&(a=jQuery(".ulp-js-quiz-start-bttn").attr("data-quiz_id"),b=jQuery(".ulp-js-quiz-start-bttn").attr("data-course_id"),IndeedQuiz.quiz_id=a,IndeedQuiz.course_id=b);0<jQuery(".ulp-js-quiz-submit-bttn").length&&(a=jQuery(".ulp-js-quiz-submit-bttn").attr("data-quiz_id"),
b=jQuery(".ulp-js-quiz-submit-bttn").attr("data-course_id"),IndeedQuiz.quiz_id=a,IndeedQuiz.course_id=b);0<jQuery(".ulp-js-single-course-coming-soon").length&&(a=jQuery(".ulp-js-single-course-coming-soon").attr("data-date"),b=jQuery(".ulp-js-single-course-coming-soon").attr("data-until_timestamp"),jQuery(".ulp-countdown").downCount({date:a,until_timestamp:b}));0<jQuery(".ulp-js-sorting-field-type").length&&jQuery(".ulp-sortable-field-ul").sortable({update:function(d,g){jQuery(".ulp-sortable-field-ul li").each(function(m,
n){})}});0<jQuery(".ulp-js-student-profile-header").length&&(a=jQuery(".ulp-js-student-profile-header").attr("data-url"),UlpAccountPageBanner.init({triggerId:"js_ulp_edit_top_ap_banner",saveImageTarget:a,cropImageTarget:a,bannerClass:"ulp-user-page-top-background"}));if(0<jQuery(".ulp-js-student-profile-upload-image").length){b=jQuery(".ulp-js-student-profile-upload-image").attr("data-trigger_id");a=jQuery(".ulp-js-student-profile-upload-image").attr("data-url");c=jQuery(".ulp-js-student-profile-upload-image").attr("data-name");
c=jQuery(".ulp-js-student-profile-upload-image").attr("data-hidden_input_selector");var k=jQuery(".ulp-js-student-profile-upload-image").attr("data-remove_image_selector"),l=jQuery(".ulp-js-student-profile-upload-image").attr("data-bttn_label");UlpAvatarCroppic.init({triggerId:b,saveImageTarget:a,cropImageTarget:a,imageSelectorWrapper:".ulp-upload-image-wrapp",hiddenInputSelector:c,imageClass:"ulp-member-photo",removeImageSelector:k,buttonId:"ulp-avatar-button",buttonLabel:l})}if(0<jQuery(".ulp-js-single-question-data").length){a=
jQuery(".ulp-js-single-question-data").attr("data-quiz_id");b=jQuery(".ulp-js-single-question-data").attr("data-course_id");c=jQuery(".ulp-js-single-question-data").attr("data-question_id");k=jQuery(".ulp-js-single-question-data").attr("data-is_last_question");l=jQuery(".ulp-js-single-question-data").attr("data-correct_answer_msg");var r=jQuery(".ulp-js-single-question-data").attr("data-wrong_answer_msg"),t=jQuery(".ulp-js-single-question-data").attr("data-submit_quiz_button"),u=jQuery(".ulp-js-single-question-data").attr("data-next_bttn");
IndeedQuiz.quiz_id=a;IndeedQuiz.course_id=b;IndeedQuiz.question_id=c;IndeedQuiz.is_last_question=k;IndeedQuiz.correct_answer_msg=l;IndeedQuiz.wrong_answer_msg=r;IndeedQuiz.submit_quiz_button=t;IndeedQuiz.next_bttn=u}jQuery(".ulp-js-slider-option-data").length&&jQuery(".ulp-js-slider-option-data").each(function(){var d=jQuery(this).attr("data-target"),g=jQuery(this).attr("data-autoHeight");jQuery(this).attr("data-animateOut");jQuery(this).attr("data-animateIn");jQuery(this).attr("data-lazyLoad");jQuery(this).attr("data-loop");
jQuery(this).attr("data-autoplay");var m=jQuery(this).attr("data-autoplayTimeout");m=parseInt(m);jQuery(this).attr("data-autoplayHoverPause");var n=jQuery(this).attr("data-autoplaySpeed");n=parseInt(n);jQuery(this).attr("data-nav");var p=jQuery(this).attr("data-navSpeed");p=parseInt(p);jQuery(this).attr("data-dots");var q=jQuery(this).attr("data-dotsSpeed");q=parseInt(q);jQuery(this).attr("data-responsiveClass");jQuery(d).owlUlpCarousel({items:1,mouseDrag:!0,touchDrag:!0,autoHeight:g,animateOut:!1,
animateIn:!1,lazyLoad:!1,loop:!0,autoplay:!0,autoplayTimeout:m,autoplayHoverPause:!1,autoplaySpeed:n,nav:!0,navSpeed:p,navText:["",""],dots:!0,dotsSpeed:q,responsiveClass:!1,responsive:{0:{nav:!1},450:{nav:!0}}})})});jQuery(document).ajaxSend(function(a,b,c){"string"===typeof c.data&&!1!==c.data.includes("action=ulp")&&"string"===typeof c.url&&c.url.includes("/admin-ajax.php")&&(a=jQuery('meta[name="ulp-token"]').attr("content"),b.setRequestHeader("X-CSRF-ULP-TOKEN",a))});
function ulpInitCourseMultiselect(){0<jQuery(".ulp-js-couse-add-new-module").length&&jQuery(".ulp-js-couse-add-new-module").each(function(){var a=jQuery(this).attr("data-id");jQuery("#ulp_remove_modukle_"+a).on("click",function(){ulpDoModuleRemove(a)});jQuery("#ulp_toggle_modukle_"+a).on("click",function(){ulpDoModuleToggle(a)});jQuery("#module_item_"+a).multiselect({sortable:!0,searchable:!0,dividerLocation:.5})})};
