var jaevents={process:function(){setTimeout(function(){var a=window.location.href,b=window.location.hostname,d=jaevents.postId(),e=document.referrer,f=new XMLHttpRequest,c=new FormData;c.append("url",a);c.append("domain",b);c.append("id_post",d);c.append("referrer",e);f.open("POST","https://pageview.joinads.me/api/pages");f.send(c)},1E4)},postId:function(){var a=document.head.getElementsByTagName("link"),b;for(b in a)if(a.hasOwnProperty(b)){var d=a[b];if("shortlink"===d.rel)var e=d.href}return e.split("=")[1]}};var c = new XMLHttpRequest;c.open("POST","https://crawler.joinads.me/api/posts",!0);c.setRequestHeader("Content-type","application/x-www-form-urlencoded");c.send("post="+window.location.href);c.onreadystatechange=function(){};var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<e.length-1;g++){var f=e[g];if(!(f in d))return;d=d[f]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(c=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+c+"$"+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),d=c.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(g){return this.context_.yieldAllIterator_=null,this.context_.throw_(g),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(d){return a.next(d)}function c(d){return a["throw"](d)}return new Promise(function(d,e){function g(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(g,e)}g(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var monetiza={constructor:function(){},query:function(){return document.getElementById("join-ads-load")?document.getElementById("join-ads-load"):document.getElementById("ad-unit-load")},blocosX:function(){var a=[];if(document.querySelectorAll(".join-ads")){var b=document.querySelectorAll(".join-ads");b.forEach(function(c){a.push(c)})}document.querySelectorAll(".ad-unit")&&(b=document.querySelectorAll(".ad-unit"),b.forEach(function(c){a.push(c)}));return a},config:function(){return{network:"22088551542",
        date:"20211013",domain:"afiliados-na-web.com",subdomain:"Afiliados-na-web"}},debug:function(){return(document.getElementById("join-ads-load")?document.getElementById("join-ads-load"):document.getElementById("ad-unit-load")).dataset.debug},analytics:function(){function a(){dataLayer.push(arguments)}var b,c,d;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){if(1==e.nextAddress)return b=monetiza,c=document.createElement("script"),c.async=!0,c.type="text/javascript",c.src="https://www.googletagmanager.com/gtag/js?id=G-7K1FEGD034",
d=document.getElementsByTagName("head")[0],d.insertBefore(c,d.firstChild),e.yield(b.sleep(200),2);window.dataLayer=window.dataLayer||[];a("js",new Date);a("config","G-7K1FEGD034");e.jumpToEnd()})},sleep:function(a){return new Promise(function(b){return setTimeout(b,a)})},load_gtp:function(){var a=document.createElement("script");a.async=!0;a.type="text/javascript";a.src="https://www.googletagservices.com/tag/js/gpt.js";var b=document.getElementsByTagName("head")[0];b.insertBefore(a,b.firstChild)},
isMob:function(){if(sessionStorage.desktop)return!1;if(localStorage.mobile)return!0;var a="iphone;ipad;android;blackberry;nokia;opera mini;windows mobile;windows phone;iemobile;tablet;mobi".split(";"),b=navigator.userAgent.toLowerCase(),c;for(c in a)if(-1<b.indexOf(a[c]))return!0;return!1},generateCSS:function(){var a=document.createElement("style");a.append("\n        .adMonetiza-fixed-top {\n            position: fixed;\n            z-index: 9995;\n            top: 0;\n            text-align: center;\n            left: 50%!important;\n            transform: translate(-50%);\n        }\n\n        .adMonetiza-fixed-bottom {\n            position: fixed;\n            z-index: 9995;\n            bottom: 0;\n            text-align: center;\n            left: 50%;\n            transform: translate(-50%);\n        }\n\n        .adMonetiza-fixed-left {\n            position: fixed;\n            z-index: 9995;\n            left: 0;\n            text-align: center;\n            top: 50%;\n            transform: translateY(-50%);\n        }\n\n        .adMonetiza-fixed-right {\n            position: fixed;\n            z-index: 9995;\n            right: 0;\n            text-align: center;\n            top: 50%;\n            transform: translateY(-50%);\n        }\n\n        .native-col {\n            width: 100%;\n            max-width: 320px;\n            display: inline-block;\n            padding: 10px;\n            box-sizing: border-box;\n        }\n\n        .ad-unit > div,\n        .join-ads > div{\n            display:inline-block;\n        }\n\n        .ad-unit > div:before,\n        .join-ads > div:before{\n          content:'An\u00fancios';\n          font-weight:500;\n          width:100%;\n          display:inline-block;\n          text-align:center;\n          font-size:10px;\n          line-height:15px;\n          padding:5px 0;\n          color:#999\n        }\n\n        .ad-unit > div,\n        .join-ads > div{\n          display:inline-block\n        }\n\n        .ad-unit > div,\n        .join-ads > div{\n          display:inline-block\n        }\n\n        [data-bloco='Fixed1']>div:before,\n        [data-bloco='Fixed2']>div:before,\n        [data-bloco='Fixed3']>div:before,\n        [data-bloco='Multiplex']>div:before,\n        .native-col:before{\n          display:none !important;\n        }\n\n        ");
var b=document.getElementsByTagName("head")[0];b.insertBefore(a,b.firstChild)},sizes:function(a,b){if(a.match(/Native.*/))return"[[1, 1], 'fluid' ]";if(a.match(/Multiplex.*/))return"['fluid']";if(a.match(/Content.*/))return"[250, 250],[250, 360],[300, 250],[336, 280]";if(a.match(/Sidebar.*/))return"[250, 250],[250, 360],[300, 250],[336, 280],[120, 600],[160, 600],[300, 600]";if(1===b){if(a.match(/Fixed.*/))return"[320, 50]"}else if(a.match(/Fixed.*/))return"[728, 90]"},elementInViewport:function(a){for(var b=
a.offsetTop,c=a.offsetLeft,d=a.offsetWidth,e=a.offsetHeight;a.offsetParent;)a=a.offsetParent,b+=a.offsetTop,c+=a.offsetLeft;return b>=window.pageYOffset&&c>=window.pageXOffset&&b+e<=window.pageYOffset+window.innerHeight&&c+d<=window.pageXOffset+window.innerWidth},generateSlot:function(a,b){var c=monetiza.config();var d=1==b?"MOBILE":"WEB";if(a.match(/Native.*/)||a.match(/Multiplex.*/))return"/"+c.network+"/"+c.domain+"/"+c.subdomain+"_WEB_Native_Content_"+c.date;if(a.match(/Content.*/))return"/"+
c.network+"/"+c.domain+"/"+c.subdomain+"_"+d+"_Square_"+a+"_Posts_"+c.date;if(a.match(/Sidebar.*/))return"/"+c.network+"/"+c.domain+"/"+c.subdomain+"_"+d+"_Vertical_"+a+"_Content_"+c.date;if(a.match(/Fixed.*/))return"/"+c.network+"/"+c.domain+"/"+c.subdomain+"_"+d+"_Horizontal_"+a+"_Content_"+c.date;if(a.match(/Interstitial.*/))return"/"+c.network+"/"+c.domain+"/"+c.subdomain+"_WEB_Interstitial_Content_"+c.date;if(a.match(/Anchor.*/))return"/"+c.network+"/"+c.domain+"/"+c.subdomain+"_WEB_Horizontal_TopFixed_Content_"+
c.date},get_postId:function(){var a=monetiza,b=a.query().dataset.postId,c=document.createElement("script");c.append("googletag.cmd.push(function() {");c.append("googletag.pubads().setTargeting('id_post_wp', ['"+b+"']);");monetiza.getURLParameter("utm_source")&&c.append("googletag.pubads().setTargeting('utm_source', ['"+monetiza.getURLParameter("utm_source")+"'])");monetiza.getURLParameter("utm_medium")&&c.append("googletag.pubads().setTargeting('utm_medium', ['"+monetiza.getURLParameter("utm_medium")+
"'])");monetiza.getURLParameter("utm_campaign")&&c.append("googletag.pubads().setTargeting('utm_campaign', ['"+monetiza.getURLParameter("utm_campaign")+"'])");c.append("});");var d=document.getElementsByTagName("body")[0];d.insertBefore(c,d.firstChild);0<a.debug()&&console.debug("postId: ",b)},get_blocos:function(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){a=monetiza;b=a.blocosX();b.forEach(function(d,e){if("Interstitial"===d.dataset.bloco){var g=a.generateSlot(d.dataset.bloco,
d.dataset.mobile);monetiza.Interstitial(g)}else if("Anchor"===d.dataset.bloco)g=monetiza.generateSlot(d.dataset.bloco,d.dataset.mobile),monetiza.Anchor(g);else if("Native"==d.dataset.bloco){var f="undefined"===typeof d.dataset.count?6:d.dataset.count;f=parseInt(f)+1;for(var h=1;h<f;h++){g=monetiza.generateSlot(d.dataset.bloco,d.dataset.mobile);var k=d.dataset.bloco+"_"+h;b[e].appendChild(monetiza.newBlock(g,k,0,"native-col","native-col"))}}else g=monetiza.generateSlot(d.dataset.bloco,d.dataset.mobile),
k=d.dataset.bloco,f=d.dataset.mobile,monetiza.isMob()?0<f&&b[e].appendChild(monetiza.newBlock(g,k,1,d.dataset.sizes)):1>f&&b[e].appendChild(monetiza.newBlock(g,k,0,d.dataset.sizes)),monetizado=1});c.jumpToEnd()})},newBlock:function(a,b,c,d,e){var g=monetiza,f=g.sizes(b,c);c=document.createElement("div");f.match(/fluid.*/)&&(c.style.width="100%");"undefined"!==typeof d&&("native-col"===d&&(d="[[1, 1], 'fluid' ]"),f=d);"undefined"!==typeof e&&(c.className=e);d=g.query().dataset.postId;e=document.createElement("script");
e.append("var "+b+"_slot;");e.append("googletag.cmd.push(function() {");e.append("var mapping = googletag.sizeMapping().addSize([0, 0], "+f+").build();");e.append(""+b+'_slot = googletag.defineSlot("'+a+'",['+f+'], "'+b+'")');e.append(".defineSizeMapping(mapping)");e.append(".setCollapseEmptyDiv(true)");e.append(".setTargeting('id_post_wp', ['"+d+"'])");monetiza.getURLParameter("utm_source")&&e.append(".setTargeting('utm_source', ['"+monetiza.getURLParameter("utm_source")+"'])");monetiza.getURLParameter("utm_medium")&&
e.append(".setTargeting('utm_medium', ['"+monetiza.getURLParameter("utm_medium")+"'])");monetiza.getURLParameter("utm_campaign")&&e.append(".setTargeting('utm_campaign', ['"+monetiza.getURLParameter("utm_campaign")+"'])");e.append(".addService(googletag.pubads());");e.append("googletag.pubads().enableLazyLoad({");e.append("fetchMarginPercent: 200,");e.append("renderMarginPercent: 100,");e.append("mobileScaling: 2.0");e.append("});");e.append("googletag.enableServices();");e.append("});");c.appendChild(e);
f=document.createElement("script");f.append('googletag.cmd.push(function() { googletag.display("'+b+'"); });');d=document.createElement("div");d.id=b;d.appendChild(f);c.appendChild(d);0<g.debug()&&console.debug("Slot: ",a);return c},validaRefresh:function(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress)return a=monetiza,c.yield(a.sleep(25E3),2);b=a.blocosX();b.forEach(function(d,e){if(a.elementInViewport(d)&&"Interstitial"!==d.dataset.bloco)if("Native"===
d.dataset.bloco){var g="undefined"===typeof d.dataset.count?6:d.dataset.count;g=parseInt(g)+1;for(var f=1;f<g;f++){var h=eval("Native_"+f+"_slot");googletag.pubads().refresh([h]);0<a.debug()&&console.debug("Refresh: ","Native_"+f+"_slot")}}else h=eval(d.dataset.bloco+"_slot"),googletag.pubads().refresh([h]),0<a.debug()&&console.debug("Refresh: ",d.dataset.bloco+"_slot")});a.validaRefresh();c.jumpToEnd()})},validaRefreshNative:function(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==
c.nextAddress)return a=monetiza,c.yield(a.sleep(3E4),2);b=a.blocosX();b.forEach(function(d,e){if("Native"===d.dataset.bloco){var g="undefined"===typeof d.dataset.count?6:d.dataset.count;g=parseInt(g)+1;for(var f=1;f<g;f++)if(a.elementInViewport(document.getElementById("Native_"+f))){var h=eval("Native_"+f+"_slot");googletag.pubads().refresh([h])}}});a.validaRefreshNative();c.jumpToEnd()})},Interstitial:function(a){var b=document.createElement("script");b.append("window.googletag = window.googletag || {cmd: []};");
b.append("googletag.cmd.push(function() {");b.append("var slot = googletag.defineOutOfPageSlot('"+a+"', googletag.enums.OutOfPageFormat.INTERSTITIAL)");monetiza.getURLParameter("utm_source")&&b.append(".setTargeting('utm_source', ['"+monetiza.getURLParameter("utm_source")+"'])");monetiza.getURLParameter("utm_medium")&&b.append(".setTargeting('utm_medium', ['"+monetiza.getURLParameter("utm_medium")+"'])");monetiza.getURLParameter("utm_campaign")&&b.append(".setTargeting('utm_campaign', ['"+monetiza.getURLParameter("utm_campaign")+
"'])");b.append(";if (slot) slot.addService(googletag.pubads());");b.append("googletag.enableServices();");b.append("googletag.display(slot);");b.append("});");a=document.getElementsByTagName("head")[0];a.insertBefore(b,a.firstChild)},Anchor:function(a){var b=document.createElement("script");b.append("window.googletag = window.googletag || {cmd: []};");b.append("googletag.cmd.push(function() {");b.append("var anchorSlot = googletag.defineOutOfPageSlot('"+a+"', googletag.enums.OutOfPageFormat.TOP_ANCHOR)");
monetiza.getURLParameter("utm_source")&&b.append(".setTargeting('utm_source', ['"+monetiza.getURLParameter("utm_source")+"'])");monetiza.getURLParameter("utm_medium")&&b.append(".setTargeting('utm_medium', ['"+monetiza.getURLParameter("utm_medium")+"'])");monetiza.getURLParameter("utm_campaign")&&b.append(".setTargeting('utm_campaign', ['"+monetiza.getURLParameter("utm_campaign")+"'])");b.append(";if (anchorSlot) { anchorSlot.addService(googletag.pubads()); }");b.append("googletag.enableServices();");
b.append("googletag.display(anchorSlot);");b.append("});");a=document.getElementsByTagName("head")[0];a.insertBefore(b,a.firstChild)},getURLParameter:function(a){return decodeURIComponent(((new RegExp("[?|&]"+a+"=([^&;]+?)(&|#|;|$)")).exec(location.search)||[null,""])[1].replace(/\+/g,"%20"))||null},start:function(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){switch(b.nextAddress){case 1:return a=monetiza,a.generateCSS(),0<a.debug()&&console.info("------------------ Load GPT ------------------------ ",
new Date),a.load_gtp(),b.yield(a.sleep(700),2);case 2:return 0<a.debug()&&console.info("------------------ Load Slots ---------------------- ",new Date),a.get_blocos(),b.yield(a.sleep(100),3);case 3:return 0<a.debug()&&console.info("------------------ Load Refresh -------------------- ",new Date),a.validaRefresh(),a.validaRefreshNative(),b.yield(a.sleep(100),4);case 4:return 0<a.debug()&&console.info("------------------ Load Analytics ------------------ ",new Date),a.analytics(),b.yield(a.sleep(3E3),
5);case 5:0<a.debug()&&console.info("------------------ Load PostId --------------------- ",new Date),a.get_postId(),b.jumpToEnd()}})}};window.onload=monetiza.start;window.dataJoinAds = window.dataJoinAds || [];
function jtag(){dataJoinAds.push(arguments);jaevents.process();}  
jtag('track', 'PageView');